config/routes.rb
Rails.application.routes.draw do
  # Cloudflare turnstile bot challenges via bot_challenge_page gem
  post "/challenge", to: "bot_challenge_page/bot_challenge_page#verify_challenge", as: :bot_detect_challenge
  get "/challenge", to: "bot_challenge_page/bot_challenge_page#challenge"

  mount ActionCable.server => "/cable"
  
  get 'about', :to => redirect('https://gin.btaa.org/')
  get 'help', :to => redirect('https://gin.btaa.org/guides/')
  get 'robots.:format' => 'robots#robots'
  get '/centroids.json', :to => redirect('/centroids.json')

  # Tableau
  namespace :admin do
    get '/api/tableau_export', to: 'api#tableau_export'
  end

  # Feedback
  mount PointlessFeedback::Engine, :at => '/feedback'

  # Error Pages for exception handling - EWL
  match '/404' => 'errors#not_found', via: :all
  match '/500' => 'errors#internal_server_error', via: :all

  mount Blacklight::Engine => '/'
  mount BlacklightAdvancedSearch::Engine => '/'

  root to: "catalog#index"
  get '/catalog', to: redirect('/')
  concern :searchable, Blacklight::Routes::Searchable.new

  # GEOMG // Metadata Toolkit JSON-API
  # - Only JSON GET requests
  # namespace :admin do
  #  # AdvancedSearch controller
  #  get '/advanced_search' => 'advanced_search#index', constraints: lambda { |req| req.format == :json }
  #  get '/advanced_search/facets' => 'advanced_search#facets', constraints: lambda { |req| req.format == :json }
  #  get '/advanced_search/facet/:id' => 'advanced_search#facet', constraints: lambda { |req| req.format == :json }, as: 'advanced_search_facet'

  #  # Ids controller
  #  get '/api/ids' => 'ids#index', constraints: lambda { |req| req.format == :json }
  #  get '/api' => 'api#index', constraints: lambda { |req| req.format == :json }
  #  get '/api/fetch' => 'api#fetch', constraints: lambda { |req| req.format == :json }
  #  get '/api/facet/:id' => 'api#facet', constraints: lambda { |req| req.format == :json }
  # end

  get '/brand', to: 'brand#index'

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end

  get '/catalog/:id/admin' => 'catalog#admin', as: 'admin_catalog'

  # devise_for :users

  resources :suggest, only: :index, defaults: { format: 'json' }

  resource :feedback_form, path: 'feedback', only: [:new, :create]
  get 'feedback' => 'feedback_forms#new'

  concern :gbl_exportable, Geoblacklight::Routes::Exportable.new
  concern :gbl_admin_data_dictionariesable, GeoblacklightAdmin::Routes::DataDictionariesable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :gbl_exportable
    concerns :gbl_admin_data_dictionariesable
  end

  concern :gbl_wms, Geoblacklight::Routes::Wms.new
  namespace :wms do
    concerns :gbl_wms
  end

  concern :gbl_downloadable, Geoblacklight::Routes::Downloadable.new
  namespace :download do
    concerns :gbl_downloadable
  end

  resources :download, only: [:show]

  mount Geoblacklight::Engine => 'geoblacklight'

  concern :exportable, Blacklight::Routes::Exportable.new
  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

####################
# GBL‡ADMIN

# Bulk Actions
resources :bulk_actions do
  patch :run, on: :member
  patch :revert, on: :member
end

# Users
devise_for :users, skip: [:registrations]
as :user do
  get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
  get "/sign_up" => "devise/registrations#new", :as => "new_user_registration" # custom path to sign_up/registration
  get "users/edit" => "devise/registrations#edit", :as => "edit_user_registration"
  put "users" => "devise/registrations#update", :as => "user_registration"
end

namespace :admin do
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  devise_for :users

  # Root
  root to: "documents#index"

  # Assets
  # Note "assets" is Rails reserved word for routing, oops. So we use
  # asset_files.
  resources :assets, path: "asset_files" do
    collection do
      get "display_attach_form"
      post "attach_files"

      get "destroy_all"
      post "destroy_all"
    end

    post :sort, on: :collection
  end

  # Bulk Actions
  resources :bulk_actions do
    patch :run, on: :member
    patch :revert, on: :member
  end

  # Imports
  resources :imports do
    resources :mappings
    resources :import_documents, only: [:show]
    patch :run, on: :member
  end

  # Import Distributions
  resources :import_distributions do
    resources :import_document_distributions, only: [:show]
    patch :run, on: :member
  end

  # Elements
  resources :elements do
    post :sort, on: :collection
  end

  # Form Elements
  resources :form_elements do
    post :sort, on: :collection
  end
  resources :form_header, path: :form_elements, controller: :form_elements
  resources :form_group, path: :form_elements, controller: :form_elements
  resources :form_control, path: :form_elements, controller: :form_elements
  resources :form_feature, path: :form_elements, controller: :form_elements

  # Reference Types
  resources :reference_types do
    post :sort, on: :collection
  end

  # Notifications
  resources :notifications do
    put "batch", on: :collection
  end

  # Users
  get "users/index"

  # Bookmarks
  resources :bookmarks
  delete "/bookmarks", to: "bookmarks#destroy", as: :bookmarks_destroy_by_fkeys

  # Search controller
  get "/search" => "search#index"
  
  # AdvancedSearch controller
  get '/advanced_search' => 'advanced_search#index', constraints: lambda { |req| req.format == :json }
  get '/advanced_search/facets' => 'advanced_search#facets', constraints: lambda { |req| req.format == :json }
  get '/advanced_search/facet/:id' => 'advanced_search#facet', constraints: lambda { |req| req.format == :json }, as: 'advanced_search_facet'

  # Ids controller
  get '/api/ids' => 'ids#index', constraints: lambda { |req| req.format == :json }
  get '/api' => 'api#index', constraints: lambda { |req| req.format == :json }
  get '/api/fetch' => 'api#fetch', constraints: lambda { |req| req.format == :json }
  get '/api/facet/:id' => 'api#facet', constraints: lambda { |req| req.format == :json }

  # Documents
  resources :documents do
    get "admin"
    get "versions"

    collection do
      get "fetch"
    end

    # DocumentLicensedAccesses
    resources :document_licensed_accesses, path: "licensed_access" do
      collection do
        get "import"
        post "import"

        get "destroy_all"
        post "destroy_all"
      end
    end

    # Document Assets
    resources :document_assets, path: "assets" do
      collection do
        get "display_attach_form"
        post "attach_files"

        get "destroy_all"
        post "destroy_all"
      end
    end

    # Data Dictionaries
    resources :document_data_dictionaries, path: "data_dictionaries" do
      collection do
        get "import"
        post "import"

        get "destroy_all"
        post "destroy_all"
      end

      resources :document_data_dictionary_entries, path: "entries" do
        collection do
          post "sort"
          get "destroy_all"
          post "destroy_all"
        end
      end
    end

    # DocumentDownloads
    resources :document_downloads, path: "downloads" do
      collection do
        get "import"
        post "import"

        get "destroy_all"
        post "destroy_all"
      end
    end

    # Document Distributions  
    resources :document_distributions, path: "distributions" do
      collection do
        get "display_attach_form"
        post "attach_files"

        get "import"
        post "import"

        get "destroy_all"
        post "destroy_all"
      end
    end
  end

  # Document Licensed Accesses
  resources :document_licensed_accesses, path: "licensed_access" do
    collection do
      get "import"
      post "import"

      get "destroy_all"
      post "destroy_all"
    end
  end

  # Document Downloads
  resources :document_downloads, path: "downloads" do
    collection do
      get "import"
      post "import"

      get "destroy_all"
      post "destroy_all"
    end
  end

  # Document Distributions
  resources :document_distributions, path: "distributions" do
    collection do
      get "import"
      post "import"

      get "destroy_all"
      post "destroy_all"
    end
  end

  # Document Assets
  resources :document_assets, path: "assets" do
    collection do
      get "display_attach_form"
      post "attach_files"

      get "destroy_all"
      post "destroy_all"
    end
  end

  # Assets
  get "/asset_files/ingest", to: "assets#display_attach_form", as: "assets_ingest"
  post "/asset_files/ingest", to: "assets#attach_files"
  
  # DocumentAssets
  get "/documents/:id/ingest", to: "document_assets#display_attach_form", as: "asset_ingest"
  post "/documents/:id/ingest", to: "document_assets#attach_files"

  # Asset Direct Upload
  mount Kithe::AssetUploader.upload_endpoint(:cache) => "/direct_upload", :as => :direct_app_upload

  resources :collections, except: [:show]

  # Note "assets" is Rails reserved word for routing, oops. So we use
  # asset_files.
  resources :assets, path: "asset_files", except: [:new, :create] do
    member do
      put "convert_to_child_work"
    end
  end

  # @TODO
  # mount Qa::Engine => "/authorities"
    # @TODO
    authenticate :user, ->(user) { user } do
      mount Blazer::Engine, at: "blazer"
    end
  end

  # Blog redirects
  get '/blog', :to => redirect('https://sites.google.com/umn.edu/btaa-gdp/news')
  get '/blog/index.html', :to => redirect('https://sites.google.com/umn.edu/btaa-gdp/news')
  get '/blog/2016/11/15/announcing-the-btaa-geoportal.html', :to => redirect('https://sites.google.com/umn.edu/btaa-gdp/news/2016/11/15-announcing-the-btaa-geoportal?authuser=0')

app/views/advanced/_advanced_search_facets_as_select.html.erb
<% facets_from_request(facet_field_names).each do |display_facet| %>
    <% if display_facet.items.present? %>
      <div class="form-group advanced-search-facet row">
          <%= label_tag display_facet.name.parameterize, :class => "col-sm-4 control-label" do %>
              <%= facet_field_label(display_facet.name) %>
          <% end %>
      <div class="col-sm-8">
        <%= content_tag(:select, :multiple => true,
          :name   => "f_inclusive[#{display_facet.name}][]",
          :id     => display_facet.name.parameterize,
          :class  => "form-control advanced-search-facet-select chosen-select",
          data: { placeholder: "Type or select #{facet_field_label(display_facet.name).downcase.pluralize}" }) do %>
          <% display_facet.items.each do |facet_item| %>
            <%= content_tag :option, :value => facet_item.value, :selected => facet_value_checked?(display_facet.name, facet_item.value) do %>
              <%= facet_display_value(display_facet.name, facet_item.label) %>&nbsp;&nbsp;(<%= number_with_delimiter facet_item.hits %>)
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
<% end %>


<%# Publication Date is a range input %>
<% pub_date = facet_configuration_for_field(Settings.FIELDS.INDEX_YEAR) %>
<div class="form-group advanced-search-facet row">
  <%= tag.span pub_date.field.parameterize, :class => "col-sm-4 control-label" do %>
      <%= pub_date.label %>
  <% end %>
  <div class="col-sm-8 range_limit">
    <label for="range_gbl_indexYear_im_begin" class="sr-only">Begin</label>
    <%= render_range_input(pub_date.field, :begin) %> 
    – 
    <label for="range_gbl_indexYear_im_end" class="sr-only">End</label>
    <%= render_range_input(pub_date.field, :end) %>
  </div>
</div>

app/views/advanced/_advanced_search_form.html.erb
<%= form_tag blacklight_path, :class => 'advanced form-horizontal', :method => :get do  %>
  <div class="row">
    <div class="col-md-6">
      <% unless (search_context_str = render_search_to_s(advanced_search_context.permit!.to_h)).blank? %>
        <div class="constraints well search_history">
          <h4 class="advanced-search-context"><%= t 'blacklight_advanced_search.form.search_context' %></h4>
          <%= search_context_str %>
        </div>
      <% end %>

      <%= render Blacklight::HiddenSearchStateComponent.new(params: search_state.params_for_search(advanced_search_context).except(:q).to_h) %>

      <div class="input-criteria">
        <div id="guided_search">
          <%= render 'advanced/guided_search_fields' %>
        </div>
      </div>
    </div>

    <div class="col-md-5">
      <div class="limit-criteria">
        <h2 class="h3 limit-criteria-heading"><%= t('blacklight_advanced_search.form.limit_criteria_heading_html')%></h2>

        <div id="advanced_search_facets" class="limit_input">
          <%= render 'advanced_search_facets_as_select' %>
        </div>
      </div>
    </div>

    <div class="search-submit-buttons clearfix col-sm-7">
      <%= render 'advanced_search_submit_btns' %>
    </div>
  </div>
<% end %>

app/views/advanced/_advanced_search_submit_btns.html.erb
<div class="sort-buttons pull-left">
  <%= hidden_field_tag(:search_field, blacklight_config.advanced_search[:url_key]) %>
</div>

<div class="submit-buttons pull-right">
  <%= submit_tag t('blacklight_advanced_search.form.search_btn'), :class=>'btn btn-primary advanced-search-submit', :id => "advanced-search-submit" %>
</div>

app/views/advanced/_guided_search_fields.html.erb
<div class="advanced-search-field">
  <div class="search-field">
    <label for="f1" class="sr-only">Search Field One</label>
    <%= select_tag('f1', options_for_select(advanced_key_value, guided_field(:f1, 'all_fields')), {class: 'form-control'}) %>
    <div name="row1">
      <label for="q1" class="sr-only">Text Field One</label>
      <%= text_field_tag "q1", label_tag_default_for(:q1), :class => 'form-control', autocorrect: "off", autocapitalize: "off", spellcheck: "false" %>
    </div>
  </div>
  <div class="search-operators">
    <label><%= radio_button_tag("op2", "AND", guided_radio(:op2, "AND")) %> AND</label>
    <label><%= radio_button_tag("op2", "OR", guided_radio(:op2, "OR")) %> OR</label>
    <label><%= radio_button_tag("op2", "NOT", guided_radio(:op2, "NOT")) %> NOT</label>
  </div>
  <div class="search-field">
    <label for="f2" class="sr-only">Search Field Two</label>
    <%= select_tag('f2', options_for_select(advanced_key_value, guided_field(:f2, 'publisher')), {class: 'form-control'}) %>
    <div name="row2">
      <label for="q2" class="sr-only">Text Field Two</label>
      <%= text_field_tag "q2", label_tag_default_for(:q2), :class => 'form-control', autocorrect: "off", autocapitalize: "off", spellcheck: "false" %>
    </div>
  </div>
  <div class="search-operators">
    <label><%= radio_button_tag("op3", "AND", guided_radio(:op3, "AND")) %> AND</label>
    <label><%= radio_button_tag("op3", "OR", guided_radio(:op3, "OR")) %> OR</label>
    <label><%= radio_button_tag("op3", "NOT", guided_radio(:op3, "NOT")) %> NOT</label>
  </div>
  <div class="search-field">
    <label for="f3" class="sr-only">Search Field Three</label>
    <%= select_tag('f3', options_for_select(advanced_key_value, guided_field(:f3, 'title')), {class: 'form-control'}) %>
    <div name="row3">
      <label for="q3" class="sr-only">Text Field Three</label>
      <%= text_field_tag "q3", label_tag_default_for(:q3), :class => 'form-control', autocorrect: "off", autocapitalize: "off", spellcheck: "false" %>
    </div>
  </div>
  <div class="search-operators">
    <label><%= radio_button_tag("op4", "AND", guided_radio(:op4, "AND")) %> AND</label>
    <label><%= radio_button_tag("op4", "OR", guided_radio(:op4, "OR")) %> OR</label>
    <label><%= radio_button_tag("op4", "NOT", guided_radio(:op4, "NOT")) %> NOT</label>
  </div>
  <div class="search-field">
    <label for="f4" class="sr-only">Search Field Four</label>
    <%= select_tag('f4', options_for_select(advanced_key_value, guided_field(:f4, 'placename')), {class: 'form-control'}) %>
    <div name="row4">
    <label for="q4" class="sr-only">Text Field Four</label>
      <%= text_field_tag "q4", label_tag_default_for(:q4), :class => 'form-control', autocorrect: "off", autocapitalize: "off", spellcheck: "false" %>
    </div>
  </div>
</div>

app/views/advanced/_start_over_row.html.erb
<div class="col-sm-12 start-over-row">
  <div class="button--start-over">
    <%=link_to t('blacklight.search.start_over').html_safe, blacklight_advanced_search_engine.advanced_search_path, :class => "catalog_startOverLink btn btn-primary", :id=>"startOverLink" %>
  </div>
</div>

app/views/advanced/index.html.erb
<% @page_title = "Advanced Search - #{application_name}" %>
<div class="advanced-search-form col-sm-12">
  <h1 class="advanced page-header">
    <%= t('blacklight_advanced_search.form.title') %>
    <%= link_to t('blacklight_advanced_search.form.start_over'), blacklight_advanced_search_engine.advanced_search_path, :class =>"btn btn-primary pull-right clear-form" %>
  </h1>
  <%= render 'advanced_search_form' %>
</div>