config/routes.rb
Rails.application.routes.draw do
  # Cloudflare turnstile bot challenges via bot_challenge_page gem
  post "/challenge", to: "bot_challenge_page/bot_challenge_page#verify_challenge", as: :bot_detect_challenge
  get "/challenge", to: "bot_challenge_page/bot_challenge_page#challenge"

  mount ActionCable.server => "/cable"
  
  get 'about', :to => redirect('https://gin.btaa.org/')
  get 'help', :to => redirect('https://gin.btaa.org/guides/')
  get 'robots.:format' => 'robots#robots'
  get '/centroids.json', :to => redirect('/centroids.json')

  # Tableau
  namespace :admin do
    get '/api/tableau_export', to: 'api#tableau_export'
  end

  # Feedback
  mount PointlessFeedback::Engine, :at => '/feedback'

  # Error Pages for exception handling - EWL
  match '/404' => 'errors#not_found', via: :all
  match '/500' => 'errors#internal_server_error', via: :all

  mount Blacklight::Engine => '/'
  mount BlacklightAdvancedSearch::Engine => '/'

  root to: "catalog#index"
  get '/catalog', to: redirect('/')
  concern :searchable, Blacklight::Routes::Searchable.new

  # GEOMG // Metadata Toolkit JSON-API
  # - Only JSON GET requests
  # namespace :admin do
  #  # AdvancedSearch controller
  #  get '/advanced_search' => 'advanced_search#index', constraints: lambda { |req| req.format == :json }
  #  get '/advanced_search/facets' => 'advanced_search#facets', constraints: lambda { |req| req.format == :json }
  #  get '/advanced_search/facet/:id' => 'advanced_search#facet', constraints: lambda { |req| req.format == :json }, as: 'advanced_search_facet'

  #  # Ids controller
  #  get '/api/ids' => 'ids#index', constraints: lambda { |req| req.format == :json }
  #  get '/api' => 'api#index', constraints: lambda { |req| req.format == :json }
  #  get '/api/fetch' => 'api#fetch', constraints: lambda { |req| req.format == :json }
  #  get '/api/facet/:id' => 'api#facet', constraints: lambda { |req| req.format == :json }
  # end

  get '/brand', to: 'brand#index'

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end

  get '/catalog/:id/admin' => 'catalog#admin', as: 'admin_catalog'

  # devise_for :users

  resources :suggest, only: :index, defaults: { format: 'json' }

  resource :feedback_form, path: 'feedback', only: [:new, :create]
  get 'feedback' => 'feedback_forms#new'

  concern :gbl_exportable, Geoblacklight::Routes::Exportable.new
  concern :gbl_admin_data_dictionariesable, GeoblacklightAdmin::Routes::DataDictionariesable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :gbl_exportable
    concerns :gbl_admin_data_dictionariesable
  end

  concern :gbl_wms, Geoblacklight::Routes::Wms.new
  namespace :wms do
    concerns :gbl_wms
  end

  concern :gbl_downloadable, Geoblacklight::Routes::Downloadable.new
  namespace :download do
    concerns :gbl_downloadable
  end

  resources :download, only: [:show]

  mount Geoblacklight::Engine => 'geoblacklight'

  concern :exportable, Blacklight::Routes::Exportable.new
  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

####################
# GBL‡ADMIN

# Bulk Actions
resources :bulk_actions do
  patch :run, on: :member
  patch :revert, on: :member
end

# Users
devise_for :users, skip: [:registrations]
as :user do
  get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
  get "/sign_up" => "devise/registrations#new", :as => "new_user_registration" # custom path to sign_up/registration
  get "users/edit" => "devise/registrations#edit", :as => "edit_user_registration"
  put "users" => "devise/registrations#update", :as => "user_registration"
end

namespace :admin do
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  devise_for :users

  # Root
  root to: "documents#index"

  # Assets
  # Note "assets" is Rails reserved word for routing, oops. So we use
  # asset_files.
  resources :assets, path: "asset_files" do
    collection do
      get "display_attach_form"
      post "attach_files"

      get "destroy_all"
      post "destroy_all"
    end

    post :sort, on: :collection
  end

  # Bulk Actions
  resources :bulk_actions do
    patch :run, on: :member
    patch :revert, on: :member
  end

  # Imports
  resources :imports do
    resources :mappings
    resources :import_documents, only: [:show]
    patch :run, on: :member
  end

  # Import Distributions
  resources :import_distributions do
    resources :import_document_distributions, only: [:show]
    patch :run, on: :member
  end

  # Elements
  resources :elements do
    post :sort, on: :collection
  end

  # Form Elements
  resources :form_elements do
    post :sort, on: :collection
  end
  resources :form_header, path: :form_elements, controller: :form_elements
  resources :form_group, path: :form_elements, controller: :form_elements
  resources :form_control, path: :form_elements, controller: :form_elements
  resources :form_feature, path: :form_elements, controller: :form_elements

  # Reference Types
  resources :reference_types do
    post :sort, on: :collection
  end

  # Notifications
  resources :notifications do
    put "batch", on: :collection
  end

  # Users
  get "users/index"

  # Bookmarks
  resources :bookmarks
  delete "/bookmarks", to: "bookmarks#destroy", as: :bookmarks_destroy_by_fkeys

  # Search controller
  get "/search" => "search#index"
  
  # AdvancedSearch controller
  get '/advanced_search' => 'advanced_search#index', constraints: lambda { |req| req.format == :json }
  get '/advanced_search/facets' => 'advanced_search#facets', constraints: lambda { |req| req.format == :json }
  get '/advanced_search/facet/:id' => 'advanced_search#facet', constraints: lambda { |req| req.format == :json }, as: 'advanced_search_facet'

  # Ids controller
  get '/api/ids' => 'ids#index', constraints: lambda { |req| req.format == :json }
  get '/api' => 'api#index', constraints: lambda { |req| req.format == :json }
  get '/api/fetch' => 'api#fetch', constraints: lambda { |req| req.format == :json }
  get '/api/facet/:id' => 'api#facet', constraints: lambda { |req| req.format == :json }

  # Documents
  resources :documents do
    get "admin"
    get "versions"

    collection do
      get "fetch"
    end

    # DocumentLicensedAccesses
    resources :document_licensed_accesses, path: "licensed_access" do
      collection do
        get "import"
        post "import"

        get "destroy_all"
        post "destroy_all"
      end
    end

    # Document Assets
    resources :document_assets, path: "assets" do
      collection do
        get "display_attach_form"
        post "attach_files"

        get "destroy_all"
        post "destroy_all"
      end
    end

    # Data Dictionaries
    resources :document_data_dictionaries, path: "data_dictionaries" do
      collection do
        get "import"
        post "import"

        get "destroy_all"
        post "destroy_all"
      end

      resources :document_data_dictionary_entries, path: "entries" do
        collection do
          post "sort"
          get "destroy_all"
          post "destroy_all"
        end
      end
    end

    # DocumentDownloads
    resources :document_downloads, path: "downloads" do
      collection do
        get "import"
        post "import"

        get "destroy_all"
        post "destroy_all"
      end
    end

    # Document Distributions  
    resources :document_distributions, path: "distributions" do
      collection do
        get "display_attach_form"
        post "attach_files"

        get "import"
        post "import"

        get "destroy_all"
        post "destroy_all"
      end
    end
  end

  # Document Licensed Accesses
  resources :document_licensed_accesses, path: "licensed_access" do
    collection do
      get "import"
      post "import"

      get "destroy_all"
      post "destroy_all"
    end
  end

  # Document Downloads
  resources :document_downloads, path: "downloads" do
    collection do
      get "import"
      post "import"

      get "destroy_all"
      post "destroy_all"
    end
  end

  # Document Distributions
  resources :document_distributions, path: "distributions" do
    collection do
      get "import"
      post "import"

      get "destroy_all"
      post "destroy_all"
    end
  end

  # Document Assets
  resources :document_assets, path: "assets" do
    collection do
      get "display_attach_form"
      post "attach_files"

      get "destroy_all"
      post "destroy_all"
    end
  end

  # Assets
  get "/asset_files/ingest", to: "assets#display_attach_form", as: "assets_ingest"
  post "/asset_files/ingest", to: "assets#attach_files"
  
  # DocumentAssets
  get "/documents/:id/ingest", to: "document_assets#display_attach_form", as: "asset_ingest"
  post "/documents/:id/ingest", to: "document_assets#attach_files"

  # Asset Direct Upload
  mount Kithe::AssetUploader.upload_endpoint(:cache) => "/direct_upload", :as => :direct_app_upload

  resources :collections, except: [:show]

  # Note "assets" is Rails reserved word for routing, oops. So we use
  # asset_files.
  resources :assets, path: "asset_files", except: [:new, :create] do
    member do
      put "convert_to_child_work"
    end
  end

  # @TODO
  # mount Qa::Engine => "/authorities"
    # @TODO
    authenticate :user, ->(user) { user } do
      mount Blazer::Engine, at: "blazer"
    end
  end

  # Blog redirects
  get '/blog', :to => redirect('https://sites.google.com/umn.edu/btaa-gdp/news')
  get '/blog/index.html', :to => redirect('https://sites.google.com/umn.edu/btaa-gdp/news')
  get '/blog/2016/11/15/announcing-the-btaa-geoportal.html', :to => redirect('https://sites.google.com/umn.edu/btaa-gdp/news/2016/11/15-announcing-the-btaa-geoportal?authuser=0')

app/views/shared/_banner.html.erb
<div class="alert alert-warning" role="alert">
  <p class="mb-0">
    <span class="blacklight-icons blacklight-icon-lightbulb-solid">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
        <!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.-->
        <path fill="#856504" d="M480 32c0-12.9-7.8-24.6-19.8-29.6s-25.7-2.2-34.9 6.9L381.7 53c-48 48-113.1 75-181 75l-8.7 0-32 0-96 0c-35.3 0-64 28.7-64 64l0 96c0 35.3 28.7 64 64 64l0 128c0 17.7 14.3 32 32 32l64 0c17.7 0 32-14.3 32-32l0-128 8.7 0c67.9 0 133 27 181 75l43.6 43.6c9.2 9.2 22.9 11.9 34.9 6.9s19.8-16.6 19.8-29.6l0-147.6c18.6-8.8 32-32.5 32-60.4s-13.4-51.6-32-60.4L480 32zm-64 76.7L416 240l0 131.3C357.2 317.8 280.5 288 200.7 288l-8.7 0 0-96 8.7 0c79.8 0 156.5-29.8 215.3-83.3z"/>
      </svg>
    </span>
    <strong>Register now!</strong> <a target="_blank" href="https://gin.btaa.org/conference/2025/">Join the free virtual Big Ten GIS Conference </a> on 4/11/25!
  </p>
</div>

app/views/shared/_footer_app.html.haml
%div.container-fluid
  %div.row
    %div#footer-title.col-xs-12.col-lg-12
      = link_to "https://gin.btaa.org" do
        = image_tag('gin-white.png', {alt: "Big Ten Academic Alliance Logo", height: '80px'})

    %div.col-xs-12.col-lg-6

      %h3.mt-3 About & Help
      %ul.list-unstyled
        %li
          = link_to "About Us", "https://gin.btaa.org/about/about-us/"
        %li
          = link_to "Program Updates", "https://gin.btaa.org/updates"
        %li
          = link_to "Contact Us", "https://geo.btaa.org/feedback"
        %li
          = link_to "Help Guides", "https://gin.btaa.org/guides/"
        %li 
          = link_to "Tutorials", "https://gin.btaa.org/tutorials"

      %h3.mt-3 Policies
      %ul.list-unstyled
        %li
          = link_to "Harmful Language Statement", "https://gin.btaa.org/policies/harmful-language"
        %li
          = link_to "Privacy Statement", "https://btaa.org/privacy"
        %li
          = link_to "Collection Development", "https://gin.btaa.org/policies/collection-development"

      %h3.mt-3 Sponsors
      %ul.list-unstyled
        %li
          = link_to "Big Ten Academic Alliance", "https://btaa.org/"
        %li
          = link_to "BTAA Geospatial Information Network", "https://gin.btaa.org/"
        %li
          = link_to "University of Minnesota Libraries", "https://lib.umn.edu/"
    
    %div.col-xs-12.col-lg-6
      %h3.mt-3 BTAA Geoportal Collection Stories
      %ul.list-unstyled
        %li
          %strong
            = link_to "Applying Deep Learning Models to BTAA GeoPortal Collections", "https://geobtaa.blogspot.com/2025/07/applying-deep-learning-models-to-btaa.html"
          • July 1, 2025
        %li
          %strong
            = link_to "Leveraging 3D GIS to promotion and discoveries map collection", "https://geobtaa.blogspot.com/2025/05/leveraging-3d-gis-to-promotion-and.html"
          • May 8, 2025
        %li 
          %strong
            = link_to "Building the Historical Maps of New Jersey website", "https://geobtaa.blogspot.com/2025/04/building-historical-maps-of-new-jersey.html"
          • April 3, 2025
        %li
          %strong
            = link_to "Discovery of Geological Maps in the BTAA Geoportal", "https://geobtaa.blogspot.com/2025/03/discovery-of-geological-maps-in-btaa.html"
          • March 4, 2025
        %li
          %strong
            = link_to "Spanker’s Branch to Campus River", "https://geobtaa.blogspot.com/2025/01/spankers-branch-to-campus-river.html"
          • January 16, 2025

      %p
        = link_to "More Collection Stories", "https://geobtaa.blogspot.com/"
      
      %h4.mt-4 BTAA Member Libraries
      %ul.list-unstyled{style: "column-count: 2;"}
        %li
          = link_to "Indiana University", "https://libraries.indiana.edu/"
        %li
          = link_to "Michigan State University", "https://lib.msu.edu/"
        %li
          = link_to "Northwestern University", "https://www.library.northwestern.edu/"
        %li
          = link_to "Pennsylvania State University", "https://libraries.psu.edu/"
        %li
          = link_to "Purdue University", "https://www.lib.purdue.edu/"
        %li
          = link_to "Rutgers University", "https://www.libraries.rutgers.edu/"
        %li
          = link_to "The Ohio State University", "https://library.osu.edu/"
        %li
          = link_to "University of Chicago", "https://www.lib.uchicago.edu/"
        %li
          = link_to "University of Illinois", "https://www.library.illinois.edu/"
        %li
          = link_to "University of Iowa", "https://www.lib.uiowa.edu/"
        %li
          = link_to "University of Maryland", "https://www.lib.umd.edu/"
        %li
          = link_to "University of Michigan", "https://www.lib.umich.edu/"
        %li
          = link_to "University of Minnesota", "https://www.lib.umn.edu/"
        %li
          = link_to "University of Nebraska-Lincoln", "https://libraries.unl.edu/"
        %li
          = link_to "University of Oregon", "https://library.uoregon.edu/"
        %li
          = link_to "University of Washington", "https://lib.uw.edu/"
        %li
          = link_to "University of Wisconsin-Madison", "https://www.library.wisc.edu/"

app/views/shared/_footer_umn.html.haml
%div.container-fluid
  %div.row
    %div#footer-lib.col-xs-12.col-lg-12
      %div.pull-left
        %p
          The technical infrastructure for this project is provided by the University of Minnesota Libraries Web Development department.

        %ul.list-horizontal
          %li
            %a{href:'https://www.lib.umn.edu/about/privacy'} Privacy Statement
          %li
            %a{href:'https://policy.umn.edu/it/itresources'} Acceptable Use of IT Resources

app/views/shared/_header_navbar.html.erb
<header aria-label="Primary">
  <div id='application-header' class='container-fluid'>
    <nav id="header-navbar" class="navbar navbar-expand-md navbar-dark topbar" role="navigation">
      <div id="b1g-header-navbar">
        <%= link_to image_tag('btaa-logo-white.png', {height: '80px', alt: 'Big Ten Academic Alliance', style:'margin:0.25rem 0px'}), root_path, { id: 'btaa-logo' } %>
      </div>
      <h1><%=link_to "Geoportal", root_path, class: "navbar-brand" %></h1>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#user-util-collapse" aria-controls="user-util-collapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-md-end" id="user-util-collapse">
        <%= render :partial=>'/user_util_links' %>
      </div>
    </nav>
  </div>
</header>

<% if controller_name == 'catalog' && has_search_parameters? %>
  <section id="home-search" aria-label='search'>
    <div id="search-bar">
      <div class="container-fluid">
        <div class='row'>
          <div class='col-xs-12 col-sm-12'>
            <%= render_search_bar %>
          </div>
        </div>
      </div>
    </div>
  </section>
<% end %>

app/views/shared/_javascript_behaviors.html.erb
<script>
  Blacklight.onLoad(function() {
    $('.gbl-display-note').linkify({ target: "_blank" });
    $('.truncate-abstract').linkify({ target: "_blank" });
    $('.blacklight-dct_rights_sm.col-md-9').linkify({ target: "_blank" });
    $('.blacklight-dct_license_sm.col-md-9').linkify({ target: "_blank" });
    $('.modal-body').linkify({ target: "_blank" });
    $('.document-metadata').linkify({ target: "_blank" });
  });
</script>

app/views/shared/_matomo_analytics.html.erb
<!-- Matomo -->
<script>
  var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="https://apps.lib.umn.edu/matomo/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '9']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Matomo Code -->

app/views/shared/_navbar_blazer.html.erb
<nav class="navbar navbar-default" style="border-bottom: 1px solid #CCC; box-shadow: 0 10px 16px 0 rgb(0 0 0 / 10%); margin-bottom: 2rem;">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">
        <strong style="color:black;">GBL♦Admin</strong>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="nav-item">
          <%= link_to "Blazer &middot; Business Intelligence Tools".html_safe, '/blazer', {class: 'nav-link'} if current_user %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_start_over_row.html.erb
<div class="col-sm-12 start-over-row">
  <div class="button--start-over">
    <%=link_to t('blacklight.search.start_over').html_safe, root_path, :class => "catalog_startOverLink btn btn-primary", :id=>"startOverLink" %>
  </div>
</div>

app/views/shared/_user_util_links.html.erb
<ul class="navbar-nav">
  <%= render_nav_actions do |config, action|%>
    <li class="nav-item"><%= action %></li>
  <% end %>

  <% if has_user_authentication_provider? %>
    <% if current_user %>

    <% if current_user.admin? %>
        <li class="nav-item">
          <%= link_to "GBL♦Admin", admin_documents_path, {class: 'nav-link'} %>
        </li>
      <% end %>

    <li class="nav-item">
      <%= link_to "Sign out", destroy_user_session_path, { :method => :delete, class: 'nav-link'} %>
    </li>

    <% unless current_user.to_s.blank? -%>
    <li class="nav-item">
      <%= link_to(current_user.email, edit_user_registration_path, {class: 'nav-link'}) %>
    </li>
    <% end %>
    <% else %>
    <li class="nav-item">
      <%= link_to "Sign in", new_user_session_path, class: 'nav-link' %>
    </li>
    <% end %>
  <% end %>
</ul>