config/routes.rb
Rails.application.routes.draw do
  # Cloudflare turnstile bot challenges via bot_challenge_page gem
  post "/challenge", to: "bot_challenge_page/bot_challenge_page#verify_challenge", as: :bot_detect_challenge
  get "/challenge", to: "bot_challenge_page/bot_challenge_page#challenge"

  mount ActionCable.server => "/cable"
  
  get 'about', :to => redirect('https://gin.btaa.org/')
  get 'help', :to => redirect('https://gin.btaa.org/guides/')
  get 'robots.:format' => 'robots#robots'
  get '/centroids.json', :to => redirect('/centroids.json')

  # Tableau
  namespace :admin do
    get '/api/tableau_export', to: 'api#tableau_export'
  end

  # Feedback
  mount PointlessFeedback::Engine, :at => '/feedback'

  # Error Pages for exception handling - EWL
  match '/404' => 'errors#not_found', via: :all
  match '/500' => 'errors#internal_server_error', via: :all

  mount Blacklight::Engine => '/'
  mount BlacklightAdvancedSearch::Engine => '/'

  root to: "catalog#index"
  get '/catalog', to: redirect('/')
  concern :searchable, Blacklight::Routes::Searchable.new

  # GEOMG // Metadata Toolkit JSON-API
  # - Only JSON GET requests
  # namespace :admin do
  #  # AdvancedSearch controller
  #  get '/advanced_search' => 'advanced_search#index', constraints: lambda { |req| req.format == :json }
  #  get '/advanced_search/facets' => 'advanced_search#facets', constraints: lambda { |req| req.format == :json }
  #  get '/advanced_search/facet/:id' => 'advanced_search#facet', constraints: lambda { |req| req.format == :json }, as: 'advanced_search_facet'

  #  # Ids controller
  #  get '/api/ids' => 'ids#index', constraints: lambda { |req| req.format == :json }
  #  get '/api' => 'api#index', constraints: lambda { |req| req.format == :json }
  #  get '/api/fetch' => 'api#fetch', constraints: lambda { |req| req.format == :json }
  #  get '/api/facet/:id' => 'api#facet', constraints: lambda { |req| req.format == :json }
  # end

  get '/brand', to: 'brand#index'

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
  end

  get '/catalog/:id/admin' => 'catalog#admin', as: 'admin_catalog'

  # devise_for :users

  resources :suggest, only: :index, defaults: { format: 'json' }

  resource :feedback_form, path: 'feedback', only: [:new, :create]
  get 'feedback' => 'feedback_forms#new'

  concern :gbl_exportable, Geoblacklight::Routes::Exportable.new
  concern :gbl_admin_data_dictionariesable, GeoblacklightAdmin::Routes::DataDictionariesable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :gbl_exportable
    concerns :gbl_admin_data_dictionariesable
  end

  concern :gbl_wms, Geoblacklight::Routes::Wms.new
  namespace :wms do
    concerns :gbl_wms
  end

  concern :gbl_downloadable, Geoblacklight::Routes::Downloadable.new
  namespace :download do
    concerns :gbl_downloadable
  end

  resources :download, only: [:show]

  mount Geoblacklight::Engine => 'geoblacklight'

  concern :exportable, Blacklight::Routes::Exportable.new
  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

####################
# GBL‡ADMIN

# Bulk Actions
resources :bulk_actions do
  patch :run, on: :member
  patch :revert, on: :member
end

# Users
devise_for :users, skip: [:registrations]
as :user do
  get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
  get "/sign_up" => "devise/registrations#new", :as => "new_user_registration" # custom path to sign_up/registration
  get "users/edit" => "devise/registrations#edit", :as => "edit_user_registration"
  put "users" => "devise/registrations#update", :as => "user_registration"
end

namespace :admin do
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  devise_for :users

  # Root
  root to: "documents#index"

  # Assets
  # Note "assets" is Rails reserved word for routing, oops. So we use
  # asset_files.
  resources :assets, path: "asset_files" do
    collection do
      get "display_attach_form"
      post "attach_files"

      get "destroy_all"
      post "destroy_all"
    end

    post :sort, on: :collection
  end

  # Bulk Actions
  resources :bulk_actions do
    patch :run, on: :member
    patch :revert, on: :member
  end

  # Imports
  resources :imports do
    resources :mappings
    resources :import_documents, only: [:show]
    patch :run, on: :member
  end

  # Import Distributions
  resources :import_distributions do
    resources :import_document_distributions, only: [:show]
    patch :run, on: :member
  end

  # Elements
  resources :elements do
    post :sort, on: :collection
  end

  # Form Elements
  resources :form_elements do
    post :sort, on: :collection
  end
  resources :form_header, path: :form_elements, controller: :form_elements
  resources :form_group, path: :form_elements, controller: :form_elements
  resources :form_control, path: :form_elements, controller: :form_elements
  resources :form_feature, path: :form_elements, controller: :form_elements

  # Reference Types
  resources :reference_types do
    post :sort, on: :collection
  end

  # Notifications
  resources :notifications do
    put "batch", on: :collection
  end

  # Users
  get "users/index"

  # Bookmarks
  resources :bookmarks
  delete "/bookmarks", to: "bookmarks#destroy", as: :bookmarks_destroy_by_fkeys

  # Search controller
  get "/search" => "search#index"
  
  # AdvancedSearch controller
  get '/advanced_search' => 'advanced_search#index', constraints: lambda { |req| req.format == :json }
  get '/advanced_search/facets' => 'advanced_search#facets', constraints: lambda { |req| req.format == :json }
  get '/advanced_search/facet/:id' => 'advanced_search#facet', constraints: lambda { |req| req.format == :json }, as: 'advanced_search_facet'

  # Ids controller
  get '/api/ids' => 'ids#index', constraints: lambda { |req| req.format == :json }
  get '/api' => 'api#index', constraints: lambda { |req| req.format == :json }
  get '/api/fetch' => 'api#fetch', constraints: lambda { |req| req.format == :json }
  get '/api/facet/:id' => 'api#facet', constraints: lambda { |req| req.format == :json }

  # Documents
  resources :documents do
    get "admin"
    get "versions"

    collection do
      get "fetch"
    end

    # DocumentLicensedAccesses
    resources :document_licensed_accesses, path: "licensed_access" do
      collection do
        get "import"
        post "import"

        get "destroy_all"
        post "destroy_all"
      end
    end

    # Document Assets
    resources :document_assets, path: "assets" do
      collection do
        get "display_attach_form"
        post "attach_files"

        get "destroy_all"
        post "destroy_all"
      end
    end

    # Data Dictionaries
    resources :document_data_dictionaries, path: "data_dictionaries" do
      collection do
        get "import"
        post "import"

        get "destroy_all"
        post "destroy_all"
      end

      resources :document_data_dictionary_entries, path: "entries" do
        collection do
          post "sort"
          get "destroy_all"
          post "destroy_all"
        end
      end
    end

    # DocumentDownloads
    resources :document_downloads, path: "downloads" do
      collection do
        get "import"
        post "import"

        get "destroy_all"
        post "destroy_all"
      end
    end

    # Document Distributions  
    resources :document_distributions, path: "distributions" do
      collection do
        get "display_attach_form"
        post "attach_files"

        get "import"
        post "import"

        get "destroy_all"
        post "destroy_all"
      end
    end
  end

  # Document Licensed Accesses
  resources :document_licensed_accesses, path: "licensed_access" do
    collection do
      get "import"
      post "import"

      get "destroy_all"
      post "destroy_all"
    end
  end

  # Document Downloads
  resources :document_downloads, path: "downloads" do
    collection do
      get "import"
      post "import"

      get "destroy_all"
      post "destroy_all"
    end
  end

  # Document Distributions
  resources :document_distributions, path: "distributions" do
    collection do
      get "import"
      post "import"

      get "destroy_all"
      post "destroy_all"
    end
  end

  # Document Assets
  resources :document_assets, path: "assets" do
    collection do
      get "display_attach_form"
      post "attach_files"

      get "destroy_all"
      post "destroy_all"
    end
  end

  # Assets
  get "/asset_files/ingest", to: "assets#display_attach_form", as: "assets_ingest"
  post "/asset_files/ingest", to: "assets#attach_files"
  
  # DocumentAssets
  get "/documents/:id/ingest", to: "document_assets#display_attach_form", as: "asset_ingest"
  post "/documents/:id/ingest", to: "document_assets#attach_files"

  # Asset Direct Upload
  mount Kithe::AssetUploader.upload_endpoint(:cache) => "/direct_upload", :as => :direct_app_upload

  resources :collections, except: [:show]

  # Note "assets" is Rails reserved word for routing, oops. So we use
  # asset_files.
  resources :assets, path: "asset_files", except: [:new, :create] do
    member do
      put "convert_to_child_work"
    end
  end

  # @TODO
  # mount Qa::Engine => "/authorities"
    # @TODO
    authenticate :user, ->(user) { user } do
      mount Blazer::Engine, at: "blazer"
    end
  end

  # Blog redirects
  get '/blog', :to => redirect('https://sites.google.com/umn.edu/btaa-gdp/news')
  get '/blog/index.html', :to => redirect('https://sites.google.com/umn.edu/btaa-gdp/news')
  get '/blog/2016/11/15/announcing-the-btaa-geoportal.html', :to => redirect('https://sites.google.com/umn.edu/btaa-gdp/news/2016/11/15-announcing-the-btaa-geoportal?authuser=0')

app/views/catalog/_access_links.html.haml
%a{data:{toggle: 'popover', content:'This resource requires authentication through one of the following institutions. Select your institution for access.'}, title: 'Licensed Resource', }
  = geoblacklight_icon(document[Settings.FIELDS.RIGHTS])
  Licensed Resource

%div.access-links.list-group
  - b1g_access_links(@document).sort.each do |key,value|
    - if key.present?
      %a.list-group-item.list-group-item-action{href:value}
        = blacklight_icon(key.parameterize)
        = key

app/views/catalog/_document_split.html.erb
<div id="documents" class="docView col-md-12">
  <%= render documents, :as => :document %>
</div>

app/views/catalog/_index_mapview_default.html.erb
<% # header bar for doc items in index view -%>
<% counter = document_counter_with_offset(document_counter) %>
<%= content_tag :div, class: 'documentHeader index-split row', data: { layer_id: document.id, geom: document.geometry.geojson, counter: counter } do %>
  <h3 class="index_title col">
    <% counter = document_counter_with_offset(document_counter) %>
    <span class="document-counter">
      <%= t('blacklight.search.documents.counter', :counter => counter) if counter %>
    </span>
    <%= link_to_document document, counter: counter %>
  </h3>
  <div class="document-wrapper">
    <div class='col-xs-11'>
      <div class='media'>
        <% if thumb_to_render?(document&.model) %>
          <%= image_tag document&.model&.thumbnail&.file_url(:thumb_standard_2X) %>
        <%- else %>
          <span class="icon square mr-3">
            <%= geoblacklight_icon(document[Settings.FIELDS.RESOURCE_CLASS]&.first, classes: 'svg_tooltip') %>
          </span>
        <%- end %>
        <div class='media-body'>
          <p><%= geoblacklight_present(:index_fields_display, document) %></p>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/catalog/_search_form.html.erb
<%= render(Blacklight::SearchBarComponent.new(
      url: search_action_url,
      advanced_search_url: blacklight_advanced_search_engine.advanced_search_path(search_state.to_h),
      params: search_state.params_for_search.except(:qt),
      search_fields: Deprecation.silence(Blacklight::ConfigurationHelperBehavior) { search_fields },
      presenter: presenter,
      autocomplete_path: search_action_path(action: :suggest))) %>

app/views/catalog/_show.html.erb
<% # BTAA Customization — Intentionally empty %>

app/views/catalog/_show_downloads.html.erb
<% document ||= @document %>

<% if document_downloadable? %>
  <% if document.direct_download.present? || document.hgl_download.present? || document.iiif_download.present? || document.download_types.present? %>
    <div class="card mt-4">
      <%# the dropdown-toggle class gives us the little arrow %>
      <div class="card-header">
        <h2 class="mb-0 h6">Download</h2>
      </div>
      <div class="card-body">
        <ul class="list-group list-group-flush">
          <%= render 'show_downloads_collapse' %>
        </ul>
      </div>
    </div>
  <% end %>
<% elsif document.restricted? && document.same_institution? %>
  <div class="card authentication">
    <div class="card-header">
      <%= link_to t('geoblacklight.tools.login_to_view'), new_user_session_path(referrer: request.original_url), class: ['btn', 'btn-default'] %>
    </div>
  </div>
<% end %>

app/views/catalog/_show_downloads_collapse.html.erb
<%# Renders the options of the downloads dropdown button %>
<% document ||= @document %>

<% if document.direct_download.present? %>
  <% if document.direct_download[:download].is_a? Array %>
    <% document.direct_download[:download].each do |download| %>
      <li class="list-group-item"><%= download_link_file(download['label'], document.id, download['url']) %></li>
    <% end %>
  <% end %>
  <% if document.direct_download[:download].is_a? String %>
    <li class="list-group-item"><%= download_link_file(download_text(document.file_format), document.id, document.direct_download[:download]) %></li>
  <% end %>
<% end %>

<% if document.hgl_download.present? %>
  <li class="list-group-item"><%= download_link_hgl(download_text(document.download_types.first[0]), document) %></li>
<% end %>

<% if document.iiif_download.present? %>
  <li class="list-group-item"><%= download_link_iiif %></li>
<% end %>

<% if document.download_types.present? %>
  <% document.download_types.each do |type| %>
    <li class="list-group-item"><%= download_link_generated(type.first, document) %></li>
  <% end %>
<% end %>

app/views/catalog/_show_header_default.html.erb
<h2 class="h1">
  <span itemprop="name"><%= document_presenter(document).heading %></span>
</h2>

<h3 class="h4">
  <i>
    <% if @document[Settings.FIELDS.PUBLISHER].present? %>
      <%= @document[Settings.FIELDS.PUBLISHER].join(', ') %>
    <% elsif @document[Settings.FIELDS.CREATOR].present? %>
      <%= @document[Settings.FIELDS.CREATOR]&.join(', ') %>
    <% elsif @document[Settings.FIELDS.PROVIDER].present? %>
      <%= @document[Settings.FIELDS.PROVIDER] %>
    <% end %>
    <% if @document[Settings.FIELDS.INDEX_YEAR].present? %>
      &middot;
      <%= @document[Settings.FIELDS.INDEX_YEAR].join(', ') %>
    <% end %>
  </i>
  <a class="btn btn-sm btn-outline-primary mb-1 pull-right" href="#metadata">Full Details</a>
</h3>

app/views/catalog/_show_item_pagination.html.erb
<div class="d-flex justify-content-between bd-highlight mb-3">
  <div>
    <% if current_search_session %>
      <%= link_to btaa_link_back_to_catalog do %>
        <span class="blacklight-icons link-color">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.--><path d="M48 256a208 208 0 1 1 416 0A208 208 0 1 1 48 256zm464 0A256 256 0 1 0 0 256a256 256 0 1 0 512 0zM217.4 376.9c4.2 4.5 10.1 7.1 16.3 7.1c12.3 0 22.3-10 22.3-22.3l0-57.7 96 0c17.7 0 32-14.3 32-32l0-32c0-17.7-14.3-32-32-32l-96 0 0-57.7c0-12.3-10-22.3-22.3-22.3c-6.2 0-12.1 2.6-16.3 7.1L117.5 242.2c-3.5 3.8-5.5 8.7-5.5 13.8s2 10.1 5.5 13.8l99.9 107.1z"/></svg>
        </span>
        Back
      <% end %>
    <% end %>
  </div>

  <%= render(Blacklight::SearchContextComponent.new(search_context: @search_context, search_session: search_session)) if search_session['document_id'] == @document.id %>

  <div>
    <% if current_search_session %>
      <%= link_to root_path(utf8: '✓', q: '', search_field: 'all_fields'), class: "catalog_startOverLink", id: "startOverLink" do %>
        Clear
        <span class="blacklight-icons link-color">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.7.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2025 Fonticons, Inc.--><path d="M256 48a208 208 0 1 1 0 416 208 208 0 1 1 0-416zm0 464A256 256 0 1 0 256 0a256 256 0 1 0 0 512zM175 175c-9.4 9.4-9.4 24.6 0 33.9l47 47-47 47c-9.4 9.4-9.4 24.6 0 33.9s24.6 9.4 33.9 0l47-47 47 47c9.4 9.4 24.6 9.4 33.9 0s9.4-24.6 0-33.9l-47-47 47-47c9.4-9.4 9.4-24.6 0-33.9s-24.6-9.4-33.9 0l-47 47-47-47c-9.4-9.4-24.6-9.4-33.9 0z"/></svg>
        </span>
      <% end %>
    <% end %>
  </div>
</div>

app/views/catalog/_show_sidebar.html.erb
<div id="sidebar-content" class="sticky-top">
  <div class="gbl-admin">
    <%= render :partial => "show_gbl_admin" %>
  </div>

  <%= render :partial => 'show_sidebar_static_map' if render_sidebar_map?(@document) %>

  <div class="downloads mb-4">
    <%= render :partial => "show_downloads" %>
  </div>

  <%= render :partial => 'show_tools' %>

  <%= render :partial => "show_sidebar_citation" %>

  <% if georeferenceable? %>
    <%= render :partial => "allmaps/sidebar/allmaps" %>
  <% end %>

  <div class="sidebar-buttons">
  </div>

  <% unless @document.more_like_this.empty? %>
    <div class="card">
      <div class="card-header">More Like This</div>
      <div class="card-body">
        <%= render :collection => @document.more_like_this, :partial => 'show_more_like_this', :as => :document %>
      </div>
    </div>
  <% end %>
</div>

app/views/catalog/_show_sidebar_citation.html.erb
<div class="card citation mb-4 mt-4">
  <div class="card-header">
    <h2 class="h6 mb-0">
      Cite and Reference
    </h2>

    <button type="button" class="blacklight-modal-close close" data-dismiss="modal" aria-label="<%= t('blacklight.modal.close') %>">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="card-body">
    <ul class="list-group list-group-flush">
        <% case @document[Settings.FIELDS.RESOURCE_CLASS].present? && @document[Settings.FIELDS.RESOURCE_CLASS].join(",").downcase %>
        <% when "collections" %>
          <li class="list-group-item">
            <p>
            <% if @document[Settings.FIELDS.TITLE].present? %>
              <i><%= @document[Settings.FIELDS.TITLE] %></i>.
          <% end %>

          <% if @document[Settings.FIELDS.PUBLISHER].present? %>
              <%= @document[Settings.FIELDS.PUBLISHER].join(', ') %>.
          <% end %>

          <% if @document.references.url.present? %>
              <%= @document.references.url.endpoint %>
            <% end %>
          </p>
        </li>
      <% else %>
        <li class="list-group-item">
          <h5 class="h6">
            Citation
            <button style="position: relative; top: -0.5rem;" class="btn-sm btn-primary copy-button pull-right" type="button" onclick="copyText('citation-text', 'citation-message', 'citation')">Copy</button>
          </h5>
          <div class="well bg-light p-3 mt-2" id="citation-text" style="height: auto;">
            <%= @document[Settings.FIELDS.CREATOR]&.join(', ') || '[Creator not found]' %> (<%= citation_date(@document[Settings.FIELDS.DATE_ISSUED]) %>). <i><%= @document[Settings.FIELDS.TITLE] %></i>. <%= @document[Settings.FIELDS.PUBLISHER]&.join(', ') %>. <%= @document&.references&.url&.endpoint %> (<%= @document[Settings.FIELDS.RESOURCE_CLASS].first.downcase.singularize %>)
          </div>
          <div id="citation-message" style="opacity: 0; transition: opacity 0.5s;"></div>
        </li>

        <li class="list-group-item mt-2">
          <h5 class="h6">
            BTAA Geoportal Link
            <button style="position: relative; top: -0.5rem;" class="btn-sm btn-primary copy-button pull-right" type="button" onclick="copyPermalink()">Copy</button>
          </h5>
          <div class="input-group permalink-container mt-2">
            <input type="text" class="form-control" id="permalink-text" value="<%= url_for(:only_path => false).split("/citation")[0] %>" readonly>
          </div>
          <div id="permalink-message" style="opacity: 0; transition: opacity 0.5s;"></div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<script>
  function copyText(elementId, messageId, itemType) {
    const textElement = document.getElementById(elementId);
    const range = document.createRange();
    range.selectNodeContents(textElement);
    const selection = window.getSelection();
    selection.removeAllRanges();
    selection.addRange(range);
    navigator.clipboard.writeText(textElement.textContent).then(() => {
      const messageElement = document.getElementById(messageId);
      messageElement.textContent = `${itemType.charAt(0).toUpperCase() + itemType.slice(1)} copied to clipboard!`;
      messageElement.style.opacity = 1;
      messageElement.style.color = 'green';
      setTimeout(() => {
        messageElement.style.opacity = 0;
      }, 3000);
    }).catch(err => {
      console.error('Failed to copy: ', err);
    });
  }

  function copyPermalink() {
    const permalinkText = document.getElementById('permalink-text');
    permalinkText.select();
    navigator.clipboard.writeText(permalinkText.value).then(() => {
      const messageElement = document.getElementById('permalink-message');
      messageElement.textContent = 'Link copied to clipboard!';
      messageElement.style.opacity = 1;
      messageElement.style.color = 'green';
      setTimeout(() => {
        messageElement.style.opacity = 0;
      }, 3000);
    }).catch(err => {
      console.error('Failed to copy: ', err);
    });
  }
</script>
<style>
  .permalink-container {
    display: flex;
    align-items: center;
  }
</style>

app/views/catalog/_show_tools.html.erb
<% if show_doc_actions? %>
  <div class="card tools">
    <div class="card-header">
      <h2 class="mb-0 h6"><%= t('blacklight.tools.title') %></h2>
    </div>
    <div class="card-body">
      <ul class="list-group list-group-flush">
        <%= render_show_doc_actions @document do |config, inner| %>
          <li class="list-group-item <%= config.key %>">
          <%= inner %>
        </li>
      <% end %>
        <%= render 'show_web_services' %>
      </ul>
    </div>
  </div>
<% end %>

app/views/catalog/_show_web_services.html.erb
<% document ||= @document %>

<% if (Settings.WEBSERVICES_SHOWN & document.references.refs.map(&:type).map(&:to_s)).any? %>
  <li class="list-group-item">
    <%= link_to "Web Services",
      web_services_solr_document_path(id: document.id),
      id: "web-services-button",
      data: {blacklight_modal: "trigger"} %>
  </li>
<% end %>

app/views/catalog/view_image.html.erb
<% document ||= @document %>

<div id='viewer-container' class="col-md-8">
  <%= content_tag :div, id: 'map', data: { map: 'item', protocol: document.viewer_protocol.camelize, url: document.viewer_endpoint, 'layer-id' => document.wxs_identifier, 'map-bbox' => document.bounding_box_as_wsen, 'catalog-path'=> search_catalog_path, available: document_available?, inspect: show_attribute_table?, basemap: geoblacklight_basemap, leaflet_options: leaflet_options } do %>
  <% end %>
</div>